### ISSUE TITLE
开源邪教ncc

### ISSUE THREAD

**Issue by tonyqus** [go-webapi/webapi#55]
[新瓜又来了！DotNetCore.NPOI的前世今生](https://zhuanlan.zhihu.com/p/392670444)

[起底开源邪教NCC](https://zhuanlan.zhihu.com/p/392900974)

**Comment by johnwiichang** [comment]
This project is a golang framework.
**Please don't abuse Github.**

**Comment by tonyqus** [comment]
Sorry, I don't find a C# project in your github. I believe you used to be a .NETer, didn't it? I'm not sure what's the relationship between you and Shanyou Zhang.  But I guess you know each other very well. 

The posts are to reveal the evilness of NCC group and after everyone in China community figures out what it really is. .NET community can get rid of this group and rise up. The current .NET community in China is not the familiar community I used to work with.  I think it's time to heal this community and make .NET great again in China.
